image:
  - Visual Studio 2017

stack: python 3

environment:
    PY_DIR: C:\Python37-x64
    
platform:
  - x64

branches:
  only:
    - master

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          throw "There are newer queued builds for this pull request, failing early." }
  - cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%
  - cmd: pip install -r requirements.txt
  - cmd: pip freeze 

build_script:
  - cmd: pyinstaller.exe -w qafmgr.py
  - cmd: python makensis.py > install.nsi
  - cmd: makensis.exe install.nsi
    
artifacts:
  - path: '*.exe'
    name: myartifact
  
deploy:
  tag: $(GIT_VERSION)
  release: v$(GIT_VERSION)
  description: v$(GIT_VERSION)
  provider: GitHub
  auth_token:
    secure: bt06FOuVpHyB8zXIF1jQvTOPU1/7YGe+57IJvn/xn/YTdZxwYCNvYpF3IWQqTptv

  artifact: myartifact
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
