image:
  - Visual Studio 2017

stack: python 3

environment:
    PY_DIR: C:\Python37-x64
    
platform:
  - x64

branches:
  only:
    - master

install:
  - cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%
  - python -m pip install -r requirements.txt
  - python -m pip install pyinstaller

build_script:
  - cmd: set PYTHONPATH=C:\projects\;%PYTHONPATH%
    pyinstaller.exe -F -w qafmgr.py
    
artifacts:
  - path: 'dist/*.exe'
  
#deploy:
#  description: 'This is a test description'
#  provider: GitHub
#  auth_token:
#    secure: 4093c25baa8d19fd52ae69d0291d32aa65d0b89b 
#  artifact: dist\qafmgr.exe
#  draft: false
#  prerelease: false
#  on:
#    branch: master                 # release from master branch only
#    APPVEYOR_REPO_TAG: true        # deploy on tag push only
