image:
  - Visual Studio 2017

stack: python 3

environment:
    PY_DIR: C:\Python37-x64
    
platform:
  - x64

branches:
  only:
    - master

install:
  - cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%
#  - python -m venv myvenv
#  - cmd: myvenv\Scripts\activate.bat
  - cmd: pip install -r requirements.txt
  - cmd: pip freeze 

build_script:
  - cmd: pyinstaller.exe -w qafmgr.py
  - cmd: python makensis.py > install.nsi
  - cmd: makensis.exe install.nsi
    
artifacts:
  - path: '*.exe'
  
deploy:
  description: 'This is a test description'
  provider: GitHub
  auth_token:
    secure: bt06FOuVpHyB8zXIF1jQvTOPU1/7YGe+57IJvn/xn/YTdZxwYCNvYpF3IWQqTptv

  artifact: '*.exe'
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
#    APPVEYOR_REPO_TAG: true        # deploy on tag push only
